[package]
name = "cosmic-applet-cpu-temp"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.10"
tracing = "0.1"
sysinfo = "0.30"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["applet-token"]
